### ISSUE TITLE
Accents

### ISSUE THREAD

**Issue by afilp** [zifnab87/aor-language-greek#2]
Hi Michail,

Any idea how to get rid of the accents in capital letters?

![image](https://user-images.githubusercontent.com/7850073/34229594-8f287a12-e5dd-11e7-9c80-3e3b6c2af949.png)

Thanks!

**Comment by zifnab87** [comment]
Hi!

In contrast to other languages like French - in Greek accents need to be dropped when the words are in uppercase. Unfortunately this needs to be done in a language-by-language basis something which  aor-language-greek can't provide since admin-on-rest  doesn't take into account this edge-case.  Your best bet is to write some javascript/react code that selects elements that have the style property "text-transform: uppercase" and make replacements on each of the letters that have accents on them.  Something like that is done from:  https://github.com/ebababi/jquery-remove-upcase-accents but could be easily implemented without jquery and an extra library. 

If you make the following code run after each react component has rendered - you will get the result you want albeit in a bit hacky way:

```javascript
NodeList.prototype.forEach = Array.prototype.forEach; // a bit dangerous
var spans = document.querySelectorAll('span') //possibly needs to be more specific than all spans
  .forEach(function(el) {
     if (el.style.textTransform === "uppercase") {
        el.innerText = el.innerText.replace('Ό','Ο');
        el.innerText = el.innerText.replace('Ή','Η');
        el.innerText = el.innerText.replace('Ί','Ι');
        el.innerText = el.innerText.replace('Ώ','Ω');
        el.innerText = el.innerText.replace('Έ','Ε');
        el.innerText = el.innerText.replace('Ύ','Υ');
        el.innerText = el.innerText.replace('Ά','Α');
    }
})
```

**Comment by afilp** [comment]
Thanks!

Your suggestions are great. May I suggest this change to the proposed code? (so that you do not need the *'a bit dangerous'* part)

````
const spanList = [...document.querySelectorAll("span")]
.forEach(function(el) {
etc....
````

Another (semi)solution for not "penalizing" performance is to have 2 translations, one of them using upper case letters for whatever AOR converts to uppercase (for example: "ΔΗΜΙΟΥΡΓΙΑ". So the user can choose which version they want.

This is what I did, for example:

````
// FILE: ourMessages.js
const ourMessages = {
    aor: {
        action: {
            delete: 'ΔΙΑΓΡΑΦΗ',
            show: 'ΕΜΦΑΝΙΣΗ',
            list: 'ΛΙΣΤΑ',
            save: 'ΑΠΟΘΗΚΕΥΣΗ',
            create: 'ΔΗΜΙΟΥΡΓΙΑ',
            edit: 'ΕΠΕΞΕΡΓΑΣΙΑ',
            cancel: 'ΑΚΥΡΩΣΗ',
            refresh: 'ΑΝΑΝΕΩΣΗ',
            add_filter: 'ΠΡΟΣΘΗΚΗ ΦΙΛΤΡΟΥ',
            remove_filter: 'ΔΙΑΓΡΑΦΗ ΦΙΛΤΡΟΥ',
            back: 'ΕΠΙΣΤΡΟΦΗ'
        },
    },
    post: {
        action:
            {
                save_and_show: 'ΑΠΟΘΗΚΕΥΣΗ',
                save_and_add: 'ΑΠΟΘΗΚΕΥΣΗ ΚΑΙ ΝΕΑ ΔΗΜΙΟΥΡΓΙΑ',
            }
    }
};

export default ourMessages;
````

Then, at ``App.js``:
````
import greekMessages from 'aor-language-greek';
import ourMessages from './ourMessages.js';

const messages = {
    el: {...greekMessages, ...ourMessages},
};
````

**Comment by zifnab87** [comment]
@afilp I decided to drop the accents from the actions so that they are compatible with upper casing!

Thanks for the tip ```const spanList = [...document.querySelectorAll("span")]``` I didn't know I could do that :)
You can download version 0.0.4 from npm and it should work

**Comment by afilp** [comment]
@zifnab87 May the library also take care of these accent issues? What do you think?

![image](https://user-images.githubusercontent.com/7850073/35189354-5c0505ec-fe51-11e7-988d-555664fe103a.png)

**Comment by afilp** [comment]
@zifnab87 Can you please check your LinkedIn messages, I would like us to connect if you wish (we have common connections that we both know well).

**Comment by zifnab87** [comment]
@afilp I will drop those accents then - Sure! I checked my linkedin messages and I don't see anything relevant - have you requested a connection? Not sure which is the one out of all those pending

**Comment by zifnab87** [comment]
closed by: https://github.com/zifnab87/aor-language-greek/commit/a1eff43909071fe227c1ab081a1b8a56db9a3eb9

**Comment by afilp** [comment]
@zifnab87 Hi Michail, my linkedin is here:
https://www.linkedin.com/in/arisfilokostas/

I have made an invitation to you which is in `pending` status. I know you have hundreds of them (I have the same problem, many spammy invitations!), just visit the above link and you will find it. Thanks!
