### ISSUE TITLE
Support for "ra" ("react-admin" version 2, aka "admin-on-rest version 2)

### ISSUE THREAD

**Issue by afilp** [zifnab87/aor-language-greek#5]
Hi Michail,

I will upgrade to AOR version 2 today (now known as "react-admin" version 2).

Please check here: https://github.com/marmelab/admin-on-rest/blob/9a35244e3c0afb081ee184c93c34d0f2807fe604/UPGRADE.md#replaced-messages-by-i18nprovider-in-admin

This means that we need to change the `aor` key to `ra`. Would you like to do this? I assume in a different branch?

I think that you need to have a different package now, called "ra-language-greek" instead of a branch.

What do you think?

**Comment by afilp** [comment]
Actually, the need is to have a different npm package, like they already did with `aor-dependent-input`: they created another one for `ra`:  https://www.npmjs.com/package/ra-dependent-input

**Comment by zifnab87** [comment]
Hi I made this: https://www.npmjs.com/package/ra-language-greek - please close if it works as expected
